services:

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: harsh45
      MYSQL_DATABASE: jobquest

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pharsh45"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./BackendDevOps

    container_name: backend-container

    ports:
      - "8081:8081"

    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./FrontendDevOps

    container_name: frontend-container

    ports:
      - "5175:5175"

    depends_on:
      - backend

volumes:
  mysql-data: