spring.application.name=BackendDevOps

server.port=8081
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/jobquest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=harsh45

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect